format:
  pdf:
    mainfont: "Liberation Serif"
    sansfont: "Liberation Sans"
    monofont: "Liberation Mono"
    lang: ru
    fontsize: 12pt
    papersize: a4
    toc: true
    toc-depth: 2
    toc-title: "Содержание"
    number-sections: true
    lof: true
    lot: true
    include-in-header:
      text: |
        \let\oldtoc\tableofcontents
        \renewcommand{\tableofcontents}{\clearpage\oldtoc}
